// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//
//    var hubstaffAuthModel = HubstaffAuthModel.FromJson(jsonString);

using System;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace HI.SharedKernel.Models
{
    public partial class HsAuthModel
    {
        [JsonProperty("user")]
        public HsUser User { get; set; }
    }

    public partial class HsUser
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("last_activity")]
        public DateTimeOffset LastActivity { get; set; }

        [JsonProperty("auth_token")]
        public string AuthToken { get; set; }
    }

    public partial class HsAuthModel
    {
        public static HsAuthModel FromJson(string json) => JsonConvert.DeserializeObject<HsAuthModel>(json, HsConverter.Settings);
    }

    public static class HsSerialize
    {
        public static string ToJson(this HsAuthModel self) => JsonConvert.SerializeObject(self, HsConverter.Settings);
    }

    internal static class HsConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}